### ISSUE TITLE
maximumIgnitionTiming does not acccount timing_offset_cylinder

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5894]
Set timing_offset_cylinder for a funny engine like Harley

problem: ignition is messed up due to default minimumIgnitionTiming and maximumIgnitionTiming no longer making sense
desired: same -10 to 60 IgnitionTiming range is still producing proper results on HD

We have maximumIgnitionTiming and minimumIgnitionTiming safety feature which does not account odd file engine shapes as it probably should

timing_offset_cylinder = "I have a funny engine with cylinders not evenly spaced every 720 / N degrees". Offsets both ignition and fueling.

**Comment by mck1117** [comment]
Unless something is different on FOME, I'm not sure this is true. Clamping happens before adding the cylinder's offset, which includes both the offset in the firing order and the user-programmed cylinder offset.

**Comment by rusefillc** [comment]
> Unless something is different

it's definitely different

**Comment by rusefillc** [comment]
@FDSoftware was this resolved by https://github.com/rusefi/rusefi/pull/7957 or just relevant?

**Comment by FDSoftware** [comment]
> [@FDSoftware](https://github.com/FDSoftware) was this resolved by [#7957](https://github.com/rusefi/rusefi/pull/7957) or just relevant?

Relevant (since we add the code need for this), not fixed yet, we need to modify a bit the ignition logic for solve this issue
