### ISSUE TITLE
AuxSpeed goes to 0 after 'Burn'

### ISSUE THREAD

**Issue by zed65** [rusefi/rusefi#5907]
Every time I hit "Burn" the auxSpeed goes to zero and stays there.
After a reboot it's back again

F407 Discovery

**Comment by rusefillc** [comment]
@dron0gus any chance you can help? this is really annoying for traction control manual testing

**Comment by dron0gus** [comment]
@zed65 should be fixed in master now.
At least I see non zero speed on my discovery + signal generator after any number of burn.

**Comment by zed65** [comment]
Nope sorry, the problem is still there.
It's the auxSpeed1 and 2 (auxFreqInput1 and 2) that is the problem.
VSS has always worked as it should.

**Comment by dron0gus** [comment]
https://github.com/rusefi/rusefi/pull/6157 Aux speed sensors were not inited after config change.

**Comment by zed65** [comment]
Finally it works!!
